function result = solve_MAP(...
                G,...
                L,...
                W,...
                alpha,...
                d_obs,...
                sigma_g,...
                gamma)

Cd_inv = speye(length(d_obs))/sigma_g^2;

b = G'*(Cd_inv*d_obs) ...
  + gamma*(L'*(W*alpha));

Afun = @(x) ...
      G'*(Cd_inv*(G*x)) ...
    + gamma*(L'*(W*(L*x)));

[m_map,flag,relres,iter] = pcg(Afun,b,1e-6,500);

g_map = G*m_map;

rmse = sqrt(mean((g_map-d_obs).^2));

result.m_map = m_map;
result.g_map = g_map;
result.flag = flag;
result.relres = relres;
result.iter = iter;
result.rmse = rmse;

end